name: sync output

on:
    push:
        branches:
            - "**"
    schedule:
        - cron: "0 0 * * *"
    workflow_dispatch: {}

permissions:
    contents: write

concurrency:
    group: sync-output
    cancel-in-progress: false

jobs:
    extract:
        runs-on: ubuntu-latest
        env:
            TARGET_BRANCH: generated-output
            ENABLE_CLOUD_STORAGE: ${{ vars.ENABLE_CLOUD_STORAGE }}
        outputs:
            shouldCommit: ${{ steps.extract.outputs.shouldCommit }}
            status: ${{ steps.extract.outputs.status }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  path: script
                  fetch-depth: 0

            - name: Checkout scales
              env:
                  PRIVATE_REPO_URL: ${{ secrets.SCALES_REPOSITORY_URL }}
                  PRIVATE_REPO_TOKEN: ${{ secrets.SCALES_TOKEN }}
              run: |
                  set -euo pipefail
                  AUTH_URL="${PRIVATE_REPO_URL/https:\/\//https:\/\/x-access-token:${PRIVATE_REPO_TOKEN}@}"
                  git clone --branch ${{ env.TARGET_BRANCH }} --no-checkout --filter=blob:none "${AUTH_URL}" target
                  cd target
                  git sparse-checkout init --cone
                  git sparse-checkout set bundle.json
                  git checkout
                  ls

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "24"

            - name: Install dependencies
              run: |
                  cd script
                  npm ci

            - name: Run the script
              env:
                  RAPAE_VERSION_URL: ${{ secrets.RAPAE_VERSION_URL }}
                  RAPAE_TARGET_URL: ${{ secrets.RAPAE_TARGET_URL }}
              run: |
                  ls target
                  file target/bundle.json
                  cd script
                  npm run build
                  npm run start ../target

            - name: Extract output
              id: extract
              run: |
                  set -euxo pipefail
                  export SHOULD_COMMIT=$(jq -r '.shouldCommit' target/result.tmp)
                  export STATUS=$(jq -r '.status' target/result.tmp)
                  echo "shouldCommit=${SHOULD_COMMIT}" >> $GITHUB_OUTPUT
                  echo "status=${STATUS}" >> $GITHUB_OUTPUT
                  if [[ "${SHOULD_COMMIT}" != "true" ]]; then
                    if [[ "${STATUS}" != "0" ]]; then
                      echo "Error occurred. Exiting."
                      exit 1
                    fi
                    if [[ "${STATUS}" == "0" ]]; then
                      echo "::warning::No changes to commit. Exiting."
                      exit 0
                    fi
                  fi

            - name: Checkout scirpophaga
              uses: actions/checkout@v3
              if: steps.extract.outputs.shouldCommit == 'true'
              with:
                  repository: cuscutaceae/scirpophaga
                  path: scirpophaga
                  ref: main

            - name: Setup Rust
              if: steps.extract.outputs.shouldCommit == 'true'
              uses: dtolnay/rust-toolchain@stable

            - name: Setup Dependencies
              if: steps.extract.outputs.shouldCommit == 'true'
              run: sudo apt-get update && sudo apt-get install -y clang cmake pkg-config

            - name: Run scirpophaga
              if: steps.extract.outputs.shouldCommit == 'true'
              run: |
                  cd scirpophaga
                  cargo run -- ../target/lib.tmp/libcocos2dcpp.so > ../target/scirpophaga_key.txt

            - name: Remove temporary files
              if: steps.extract.outputs.shouldCommit == 'true'
              run: |
                  set -euxo pipefail
                  find . -type f -name "*.tmp" -delete
                  find . -type d -name "*.tmp" -empty -delete

            - name: Install AWS CLI
              id: install-aws-cli
              if: steps.extract.outputs.shouldCommit == 'true' && env.ENABLE_CLOUD_STORAGE == 'true'
              uses: unfor19/install-aws-cli-action@v1

            - name: Install Wrangler CLI
              if: steps.extract.outputs.shouldCommit == 'true' && env.ENABLE_CLOUD_STORAGE == 'true'
              run: |
                  set -euxo pipefail
                  npm install wrangler

            - name: Upload to S3
              if: steps.extract.outputs.shouldCommit == 'true' && env.ENABLE_CLOUD_STORAGE == 'true'
              env:
                  AWS_ENDPOINT_URL: ${{ secrets.AWS_ENDPOINT_URL }}
                  AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
                  CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
                  CLOUDFLARE_KV_NAMESPACE_ID: ${{ secrets.CF_KV_NAMESPACE_ID }}
                  CLOUDFLARE_KV_KEY: ${{ secrets.CF_KV_KEY }}
              run: |
                  set -euxo pipefail
                  current_timestamp=$(date +%s)
                  aws s3 sync target/ s3://${AWS_BUCKET_NAME}/versions/${current_timestamp}/ --endpoint-url "${AWS_ENDPOINT_URL}"
                  wrangler kv:key put --namespace-id="${CLOUDFLARE_KV_NAMESPACE_ID}" "${CLOUDFLARE_KV_KEY}" "${current_timestamp}"

            - name: Commit changes
              if: steps.extract.outputs.shouldCommit == 'true'
              run: |
                  set -euo pipefail
                  cd target

                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"

                  git rm --cache -r . || true
                  git add --sparse -A

                  if git diff --cached --quiet; then
                    echo "::warning::No changes to commit."
                    exit 0
                  fi

                  git commit -m "Update output ($(date -u +'%Y-%m-%dT%H:%M:%SZ'))"

            - name: Push to origin
              if: steps.extract.outputs.shouldCommit == 'true'
              env:
                  PRIVATE_REPO_URL: ${{ secrets.SCALES_REPOSITORY_URL }}
                  PRIVATE_REPO_TOKEN: ${{ secrets.SCALES_TOKEN }}
              run: |
                  set -euxo pipefail
                  cd target
                  AUTH_URL="${PRIVATE_REPO_URL/https:\/\//https:\/\/x-access-token:${PRIVATE_REPO_TOKEN}@}"
                  git push -u origin "${TARGET_BRANCH}"
